# Generated by Django 3.1.7 on 2021-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_validedform'),
    ]

    operations = [
        migrations.AddField(
            model_name='validedform',
            name='upi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
