# Generated by Django 3.1.7 on 2021-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210429_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoform',
            name='aadhar',
            field=models.CharField(default='', max_length=13),
        ),
    ]
