# Generated by Django 3.1.7 on 2021-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ngoform_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoform',
            name='bank_detail',
            field=models.TextField(default=''),
        ),
    ]
